driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 4

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[chef-analytics]
    attributes:
      chef-analytics:
        fqdn: 'analytics.chef.piab'
