driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 4

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.8
  - name: centos-7.2

transport:
  name: sftp

suites:
  - name: default
    run_list:
      - recipe[chef-analytics]
    attributes:
      chef-analytics:
        accept_license: true
        fqdn: 'analytics.chef.piab'
  - name: install-1_4_0
    run_list:
      - recipe[chef-analytics]
    attributes:
      chef-analytics:
        accept_license: true
        fqdn: 'analytics.chef.piab'
        version: '1.4.0'
